language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jensborch-github"
jdk:
  - openjdk11
script:
  - ./gradlew build
  - ./gradlew codeCoverageReport
  - ./gradlew sonarqube -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.branch.target=master --scan
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'