language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jensborch-github"
jdk:
  - oraclejdk8
before_install:
  - gradle -b wrapper.gradle wrapper
script:
  - gradle build integrationTest
  - gradle codeCoverageReport
  - gradle sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'